subject: dict = {
    'prefix': [
        "Introduction to",
        "Fundamentals of",
        "Advanced",
        "Applied",
        "Principles of",
        "Concepts of",
        "Foundations of",
        "Essentials of",
        "Overview of",
        "Theory of",
        "Comprehensive",
        "Modern",
        "Contemporary",
        "Special Topics in",
        "Core Concepts of",
        "Techniques in",
        "Methods in"
    ],

    'core': [
        # Computer Science / IT
        "Artificial Intelligence",
        "Machine Learning",
        "Deep Learning",
        "Data Science",
        "Big Data Analytics",
        "Cyber Security",
        "Ethical Hacking",
        "Software Engineering",
        "Computer Networks",
        "Cloud Computing",
        "Edge Computing",
        "Database Systems",
        "Distributed Systems",
        "Operating Systems",
        "Web Development",
        "Frontend Development",
        "Backend Development",
        "Full Stack Development",
        "Mobile App Development",
        "Game Development",
        "Human Computer Interaction",
        "Computer Graphics",
        "Computer Vision",
        "Natural Language Processing",
        "Robotics",
        "Internet of Things",
        "Embedded Systems",
        "Parallel Computing",
        "Quantum Computing",
        "Compiler Design",
        "Programming Languages",
        "Data Structures",
        "Algorithms",
        "DevOps Engineering",
        "Site Reliability Engineering",
        "Blockchain Technology",
        "Cryptography",
        "Digital Forensics",

        # Mathematics / Statistics
        "Mathematics",
        "Discrete Mathematics",
        "Linear Algebra",
        "Calculus",
        "Differential Equations",
        "Probability Theory",
        "Statistics",
        "Bayesian Statistics",
        "Numerical Methods",
        "Optimization Techniques",
        "Graph Theory",
        "Number Theory",
        "Operations Research",

        # Physics
        "Physics",
        "Classical Mechanics",
        "Quantum Mechanics",
        "Thermodynamics",
        "Electromagnetism",
        "Optics",
        "Astrophysics",
        "Particle Physics",
        "Nuclear Physics",

        # Chemistry
        "Chemistry",
        "Organic Chemistry",
        "Inorganic Chemistry",
        "Physical Chemistry",
        "Analytical Chemistry",
        "Biochemistry",
        "Industrial Chemistry",

        # Biology / Medical
        "Biology",
        "Molecular Biology",
        "Genetics",
        "Microbiology",
        "Biotechnology",
        "Bioinformatics",
        "Neuroscience",
        "Human Anatomy",
        "Physiology",
        "Pharmacology",
        "Epidemiology",

        # Engineering
        "Electrical Engineering",
        "Electronics Engineering",
        "Mechanical Engineering",
        "Civil Engineering",
        "Chemical Engineering",
        "Industrial Engineering",
        "Mechatronics",
        "Control Systems",
        "Signal Processing",
        "Power Systems",
        "Thermal Engineering",
        "Structural Engineering",

        # Business / Management
        "Business Administration",
        "Management",
        "Project Management",
        "Human Resource Management",
        "Marketing",
        "Digital Marketing",
        "Finance",
        "Accounting",
        "Entrepreneurship",
        "Supply Chain Management",
        "Operations Management",
        "Business Analytics",
        "E-Commerce",

        # Social Sciences
        "Economics",
        "Microeconomics",
        "Macroeconomics",
        "Political Science",
        "Sociology",
        "Psychology",
        "Cognitive Science",
        "Anthropology",
        "International Relations",

        # Humanities
        "Philosophy",
        "Ethics",
        "History",
        "World History",
        "Literature",
        "Linguistics",
        "Creative Writing",
        "Communication Studies",

        # Arts / Design
        "Graphic Design",
        "UI/UX Design",
        "Animation",
        "Film Studies",
        "Photography",
        "Music Theory",
        "Fine Arts",

        # Law / Education
        "Law",
        "Constitutional Law",
        "Criminal Law",
        "International Law",
        "Education",
        "Curriculum Development",
        "Instructional Design",

        # Interdisciplinary / Emerging
        "Artificial General Intelligence",
        "Explainable AI",
        "Green Computing",
        "Sustainable Development",
        "Environmental Science",
        "Climate Change Studies",
        "Smart Cities",
        "Digital Transformation",
        "Information Systems",
        "Knowledge Management"
    ],

    'suffix': [
        "I",
        "II",
        "III",
        "Basics",
        "Concepts",
        "Techniques",
        "Applications",
        "Case Studies",
        "Advanced Topics",
        "Essentials",
        "Foundations"
    ]
}